#Take the image from user then create functions to add line, rectngle, circle and text on that image.
import cv2
location = input("Enter the image location : ")
img = cv2.imread(location)
if img is None:
    print("Error loading image")
else:
    user_input = input("Choose from the following options to draw on image:\n1. Line\n2. Rectangle\n3. Circle\n4. Text\nEnter your choice (1/2/3/4): ")
    if user_input == '1':
        pt1 = input("Enter the starting point (x,y) of the line : ")
        pt2 = input("Enter the ending point (x,y) of the line : ")
        color = input("Enter the color (B,G,R) of the line : ")
        thickness = int(input("Enter the thickness of the line : "))
        pt1 = tuple(map(int, pt1.split(',')))
        pt2 = tuple(map(int, pt2.split(',')))
        color = tuple(map(int, color.split(',')))
        cv2.line(img, pt1, pt2, color, thickness)
        cv2.imshow("Line Image", img)
        cv2.waitKey(0)
        cv2.destroyAllWindows()
    elif user_input == '2':
        top_left = input("Enter the top-left corner (x,y) of the rectangle : ")
        bottom_right = input("Enter the bottom-right corner (x,y) of the rectangle : ")
        color = input("Enter the color (B,G,R) of the rectangle : ")
        thickness = int(input("Enter the thickness of the rectangle : "))
        top_left = tuple(map(int, top_left.split(',')))
        bottom_right = tuple(map(int, bottom_right.split(',')))
        color = tuple(map(int, color.split(',')))
        cv2.rectangle(img, top_left, bottom_right, color, thickness)
        cv2.imshow("Rectangle Image", img)
        cv2.waitKey(0)
        cv2.destroyAllWindows()
    elif user_input == '3':
        center = input("Enter the center (x,y) of the circle : ")
        radius = int(input("Enter the radius of the circle : "))
        color = input("Enter the color (B,G,R) of the circle : ")
        thickness = int(input("Enter the thickness of the circle (-1 for filled) : "))
        center = tuple(map(int, center.split(',')))
        color = tuple(map(int, color.split(',')))
        cv2.circle(img, center, radius, color, thickness)
        cv2.imshow("Circle Image", img)
        cv2.waitKey(0)
        cv2.destroyAllWindows()     
    elif user_input == '4':
        text = input("Enter the text to be added : ")
        org = input("Enter the bottom-left corner (x,y) of the text : ")
        color = input("Enter the color (B,G,R) of the text : ")
        font_scale = float(input("Enter the font scale (e.g., 1.0): "))
        thickness = int(input("Enter the thickness of the text : "))
        org = tuple(map(int, org.split(',')))
        color = tuple(map(int, color.split(',')))
        cv2.putText(img, text, org, cv2.FONT_HERSHEY_SIMPLEX, font_scale, color, thickness)
        cv2.imshow("Text Image", img)
        cv2.waitKey(0)
        cv2.destroyAllWindows()
    else:
        print("Invalid choice. Please select a valid option.")
